
name: ci

permissions:
  contents: write

on:
  push:
    branches: 
        - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
        - name: Check Version
          shell: bash
          id: get_version
          working-directory: "/"
          run: |
              set -euo pipefail
                if [[ -f "LATEST" ]]; then
                    echo "version=$(cat LATEST)" >> $GITHUB_OUTPUT
                fi
            #   LATEST=$(cat LATEST)
            #   echo "version=$LATEST" >> $GITHUB_OUTPUT

        - name: Create Tag
          working-directory: "/"
          if: ${{steps.get_version.outputs.version != github.ref }}
          run: |
              echo "Creating new tag: ${{steps.get_version.outputs.version}}"
              git tag "${{steps.get_version.outputs.version}}"
              git push origin "${{steps.get_version.outputs.version}}"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
