
name: tag

permissions:
  contents: write

on:
  push:
    branches: 
        - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Version
      shell: bash
      id: get_version
      run: |
        set -euo pipefail
        LATEST=$(cat LATEST)
        echo "version=$LATEST" >> $GITHUB_OUTPUT
    - name: Create Tag
      shell: bash
      if: ${{steps.get_version.outputs.version != github.ref }}
      run: |
        echo "Creating new tag: ${{steps.get_version.outputs.version}}"
        git tag "${{steps.get_version.outputs.version}}"
        git push origin "${{steps.get_version.outputs.version}}"
      env:
        GH_TOKEN: ${{ secrets.CI }}